[database]
url = "sqlite:///./test.db"

[pipeman]
holding_dir = "C:/my/test_upload"
i18n_paths_file = "C:/my/data-manager/paths.yaml"

[pipeman.plugins]
#first = ["plugin1", "plugin2"]
#last = ["plugin3", "plugin4"]
#skip = ["plugin5"]

[autoinject]
"pipeman.auth.auth.AuthenticationManager" = "pipeman.builtins.auth_db.DatabaseEntityAuthenticationManager"
"pipeman.i18n.i18n.TranslationManager" = "pipeman.builtins.i18n_yaml.translator.YamlTranslationManager"
"pipeman.i18n.i18n.LanguageDetector" = "pipeman.builtins.basic_lang_detect.detector.BasicRequestLanguageDetector"

[pipeman.i18n_yaml]
dictionary_path = "C:/my/data-manager/locales"


[pipeman.authentication]
login_route = "home"
logout_route = "logged_out"

[flask]
SECRET_KEY = "VeryModernMajorGeneral"

[logging]
version = 1

[logging.root]
level = "INFO"
handlers = ["console"]

[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "brief"
level = "INFO"
stream = "ext://sys.stdout"

[logging.formatters.brief]
format = "%(name)s [%(levelname)s]: %(message)s [%(username)s; %(remote_ip)s]"
