[pipeman]
holding_dir = "/metadb-data/holding"
i18n_paths_files = [
    "/srv/metadb/app/config/paths.yaml",
    "/metadb-config/paths.yaml"
]

[pipeman.email]
template_folders = [
    "/metadb-config/email_templates"
]

[flask]
UPLOAD_FOLDER = "/metadb-data/flask"

[pipeman.i18n_yaml]
dictionary_paths = ["/srv/metadb/app/config/locales", "/metadb-config/locales"]

[universalio]
sync_db = "/metadb-data/sync.db"

[logging]
version = 1

[logging.root]
level = "INFO"
handlers = ["console"]

[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "brief"
level = "INFO"
stream = "ext://sys.stdout"

[logging.formatters.brief]
format = "%(name)s [%(levelname)s]: %(message)s"
