gociso19115:
  display:
    en: Government of Canada ISO-19115
  extends: iso19115
  validation:
    required:
      - publication_date
      - topic_category
      - resource_maintenance_frequency
      - metadata_maintenance_frequency
      - status
      - goc_collection_type
      - goc_publisher
      - goc_subject
  fields:
    goc_collection_type:
    goc_publisher:
    goc_publication_place:
    goc_subject:
    goc_audience:
