"""empty message

Revision ID: 1b035ea6eca7
Revises: f83081dbea18
Create Date: 2023-04-28 10:56:15.123558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b035ea6eca7'
down_revision = 'f83081dbea18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_value',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_key_value')),
    sa.UniqueConstraint('key', name=op.f('uq_key_value_key'))
    )
    op.drop_index('ix_metric_metric_name', table_name='metric')
    op.drop_table('metric')
    op.create_index(op.f('ix_a_p_i_key_user_id'), 'a_p_i_key', ['user_id'], unique=False)
    op.create_index(op.f('ix_attachment_dataset_id'), 'attachment', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_organization_id'), 'dataset', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_dataset_activated_item_id_workflow_item'), 'dataset', 'workflow_item', ['activated_item_id'], ['id'])
    op.create_index(op.f('ix_entity_parent_id'), 'entity', ['parent_id'], unique=False)
    op.create_index(op.f('ix_entity_parent_type'), 'entity', ['parent_type'], unique=False)
    op.create_index(op.f('ix_entity_data_entity_id'), 'entity_data', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_data_revision_no'), 'entity_data', ['revision_no'], unique=False)
    op.create_index(op.f('ix_metadata_edition_dataset_id'), 'metadata_edition', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_metadata_edition_revision_no'), 'metadata_edition', ['revision_no'], unique=False)
    op.create_foreign_key(op.f('fk_metadata_edition_approval_item_id_workflow_item'), 'metadata_edition', 'workflow_item', ['approval_item_id'], ['id'])
    op.create_index(op.f('ix_workflow_decision_workflow_item_id'), 'workflow_decision', ['workflow_item_id'], unique=False)
    op.create_foreign_key(op.f('fk_workflow_decision_attachment_id_attachment'), 'workflow_decision', 'attachment', ['attachment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workflow_decision_attachment_id_attachment'), 'workflow_decision', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_decision_workflow_item_id'), table_name='workflow_decision')
    op.drop_constraint(op.f('fk_metadata_edition_approval_item_id_workflow_item'), 'metadata_edition', type_='foreignkey')
    op.drop_index(op.f('ix_metadata_edition_revision_no'), table_name='metadata_edition')
    op.drop_index(op.f('ix_metadata_edition_dataset_id'), table_name='metadata_edition')
    op.drop_index(op.f('ix_entity_data_revision_no'), table_name='entity_data')
    op.drop_index(op.f('ix_entity_data_entity_id'), table_name='entity_data')
    op.drop_index(op.f('ix_entity_parent_type'), table_name='entity')
    op.drop_index(op.f('ix_entity_parent_id'), table_name='entity')
    op.drop_constraint(op.f('fk_dataset_activated_item_id_workflow_item'), 'dataset', type_='foreignkey')
    op.drop_index(op.f('ix_dataset_organization_id'), table_name='dataset')
    op.drop_index(op.f('ix_attachment_dataset_id'), table_name='attachment')
    op.drop_index(op.f('ix_a_p_i_key_user_id'), table_name='a_p_i_key')
    op.create_table('metric',
    sa.Column('metric_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('value', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('source_info', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('username', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_metric')
    )
    op.create_index('ix_metric_metric_name', 'metric', ['metric_name'], unique=False)
    op.drop_table('key_value')
    # ### end Alembic commands ###
