"""empty message

Revision ID: 409c438d456a
Revises: f83081dbea18
Create Date: 2023-05-26 12:25:30.207482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409c438d456a'
down_revision = 'f83081dbea18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_value',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_key_value')),
    sa.UniqueConstraint('key', name=op.f('uq_key_value_key'))
    )
    op.create_table('translation_request',
    sa.Column('guid', sa.String(length=1024), nullable=False),
    sa.Column('lang_key', sa.String(length=16), nullable=False),
    sa.Column('source_hash', sa.String(length=128), nullable=False),
    sa.Column('source_info', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('IN_PROGRESS', 'SUCCESS', 'FAILURE', 'DELAYED', name='translationstate'), nullable=False),
    sa.Column('handler_info', sa.Text(), nullable=True),
    sa.Column('allow_reuse', sa.Boolean(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translation_request'))
    )
    op.create_index(op.f('ix_translation_request_guid'), 'translation_request', ['guid'], unique=False)
    op.create_index(op.f('ix_translation_request_lang_key'), 'translation_request', ['lang_key'], unique=False)
    op.drop_index('ix_metric_metric_name', table_name='metric')
    op.drop_table('metric')
    op.create_index(op.f('ix_a_p_i_key_user_id'), 'a_p_i_key', ['user_id'], unique=False)
    op.create_index(op.f('ix_attachment_dataset_id'), 'attachment', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_organization_id'), 'dataset', ['organization_id'], unique=False)
    op.create_index(op.f('ix_entity_parent_id'), 'entity', ['parent_id'], unique=False)
    op.create_index(op.f('ix_entity_parent_type'), 'entity', ['parent_type'], unique=False)
    op.create_index(op.f('ix_entity_data_entity_id'), 'entity_data', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_data_revision_no'), 'entity_data', ['revision_no'], unique=False)
    op.create_index(op.f('ix_metadata_edition_dataset_id'), 'metadata_edition', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_metadata_edition_revision_no'), 'metadata_edition', ['revision_no'], unique=False)
    op.create_index(op.f('ix_workflow_decision_workflow_item_id'), 'workflow_decision', ['workflow_item_id'], unique=False)
    op.add_column('workflow_item', sa.Column('object_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_item', 'object_type')
    op.drop_index(op.f('ix_workflow_decision_workflow_item_id'), table_name='workflow_decision')
    op.drop_index(op.f('ix_metadata_edition_revision_no'), table_name='metadata_edition')
    op.drop_index(op.f('ix_metadata_edition_dataset_id'), table_name='metadata_edition')
    op.drop_index(op.f('ix_entity_data_revision_no'), table_name='entity_data')
    op.drop_index(op.f('ix_entity_data_entity_id'), table_name='entity_data')
    op.drop_index(op.f('ix_entity_parent_type'), table_name='entity')
    op.drop_index(op.f('ix_entity_parent_id'), table_name='entity')
    op.drop_index(op.f('ix_dataset_organization_id'), table_name='dataset')
    op.drop_index(op.f('ix_attachment_dataset_id'), table_name='attachment')
    op.drop_index(op.f('ix_a_p_i_key_user_id'), table_name='a_p_i_key')
    op.create_table('metric',
    sa.Column('metric_name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('value', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('source_info', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('username', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_metric')
    )
    op.create_index('ix_metric_metric_name', 'metric', ['metric_name'], unique=False)
    op.drop_index(op.f('ix_translation_request_lang_key'), table_name='translation_request')
    op.drop_index(op.f('ix_translation_request_guid'), table_name='translation_request')
    op.drop_table('translation_request')
    op.drop_table('key_value')
    # ### end Alembic commands ###
