"""empty message

Revision ID: c02dacadd118
Revises: f54486f1839b
Create Date: 2026-02-02 11:06:33.194738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02dacadd118'
down_revision = 'f54486f1839b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('authority', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('uq_dataset_guid'), 'dataset', type_='unique')
    op.create_unique_constraint('unique_dataset_guid_authority', 'dataset', ['guid', 'authority'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_dataset_guid_authority', 'dataset', type_='unique')
    op.create_unique_constraint(op.f('uq_dataset_guid'), 'dataset', ['guid'])
    op.drop_column('dataset', 'authority')
    # ### end Alembic commands ###
