"""empty message

Revision ID: f3c80a31ba5e
Revises: fa16fb27765f
Create Date: 2023-03-31 10:48:53.053824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c80a31ba5e'
down_revision = 'fa16fb27765f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_a_p_i_key_created_by_user'), 'a_p_i_key', 'user', ['created_by'], ['id'])
    op.add_column('config_registry', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('config_registry', sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_config_registry_created_by_user'), 'config_registry', 'user', ['created_by'], ['id'])
    op.add_column('dataset', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_dataset_created_by_user'), 'dataset', 'user', ['created_by'], ['id'])
    op.add_column('entity', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_entity_created_by_user'), 'entity', 'user', ['created_by'], ['id'])
    op.add_column('entity_data', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('entity_data', sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_entity_data_created_by_user'), 'entity_data', 'user', ['created_by'], ['id'])
    op.add_column('group', sa.Column('restricted_access', sa.Boolean(), nullable=True))
    op.add_column('group', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('group', sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_group_created_by_user'), 'group', 'user', ['created_by'], ['id'])
    op.add_column('metadata_edition', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('metadata_edition', sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_metadata_edition_created_by_user'), 'metadata_edition', 'user', ['created_by'], ['id'])
    op.add_column('organization', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('organization', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization', sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_organization_created_by_user'), 'organization', 'user', ['created_by'], ['id'])
    op.add_column('user', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_user_created_by_user'), 'user', 'user', ['created_by'], ['id'])
    op.add_column('vocabulary_term', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('vocabulary_term', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vocabulary_term', sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_vocabulary_term_created_by_user'), 'vocabulary_term', 'user', ['created_by'], ['id'])
    op.add_column('workflow_decision', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('workflow_decision', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_decision', sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_workflow_decision_created_by_user'), 'workflow_decision', 'user', ['created_by'], ['id'])
    op.add_column('workflow_item', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('workflow_item', sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_workflow_item_created_by_user'), 'workflow_item', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workflow_item_created_by_user'), 'workflow_item', type_='foreignkey')
    op.drop_column('workflow_item', 'modified_date')
    op.drop_column('workflow_item', 'created_by')
    op.drop_constraint(op.f('fk_workflow_decision_created_by_user'), 'workflow_decision', type_='foreignkey')
    op.drop_column('workflow_decision', 'modified_date')
    op.drop_column('workflow_decision', 'created_date')
    op.drop_column('workflow_decision', 'created_by')
    op.drop_constraint(op.f('fk_vocabulary_term_created_by_user'), 'vocabulary_term', type_='foreignkey')
    op.drop_column('vocabulary_term', 'modified_date')
    op.drop_column('vocabulary_term', 'created_date')
    op.drop_column('vocabulary_term', 'created_by')
    op.drop_constraint(op.f('fk_user_created_by_user'), 'user', type_='foreignkey')
    op.drop_column('user', 'modified_date')
    op.drop_column('user', 'created_date')
    op.drop_column('user', 'created_by')
    op.drop_constraint(op.f('fk_organization_created_by_user'), 'organization', type_='foreignkey')
    op.drop_column('organization', 'modified_date')
    op.drop_column('organization', 'created_date')
    op.drop_column('organization', 'created_by')
    op.drop_constraint(op.f('fk_metadata_edition_created_by_user'), 'metadata_edition', type_='foreignkey')
    op.drop_column('metadata_edition', 'modified_date')
    op.drop_column('metadata_edition', 'created_by')
    op.drop_constraint(op.f('fk_group_created_by_user'), 'group', type_='foreignkey')
    op.drop_column('group', 'modified_date')
    op.drop_column('group', 'created_date')
    op.drop_column('group', 'created_by')
    op.drop_column('group', 'restricted_access')
    op.drop_constraint(op.f('fk_entity_data_created_by_user'), 'entity_data', type_='foreignkey')
    op.drop_column('entity_data', 'modified_date')
    op.drop_column('entity_data', 'created_by')
    op.drop_constraint(op.f('fk_entity_created_by_user'), 'entity', type_='foreignkey')
    op.drop_column('entity', 'created_by')
    op.drop_constraint(op.f('fk_dataset_created_by_user'), 'dataset', type_='foreignkey')
    op.drop_column('dataset', 'created_by')
    op.drop_constraint(op.f('fk_config_registry_created_by_user'), 'config_registry', type_='foreignkey')
    op.drop_column('config_registry', 'modified_date')
    op.drop_column('config_registry', 'created_date')
    op.drop_constraint(op.f('fk_a_p_i_key_created_by_user'), 'a_p_i_key', type_='foreignkey')
    # ### end Alembic commands ###
