"""Add guid to entities

Revision ID: f54486f1839b
Revises: 64dfbebe0ba8
Create Date: 2026-01-05 09:14:51.511798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54486f1839b'
down_revision = '64dfbebe0ba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_dataset_activated_item_id_workflow_item'), 'dataset', 'workflow_item', ['activated_item_id'], ['id'])
    op.add_column('entity', sa.Column('guid', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_entity_guid'), 'entity', ['guid'], unique=False)
    op.create_foreign_key(op.f('fk_metadata_edition_approval_item_id_workflow_item'), 'metadata_edition', 'workflow_item', ['approval_item_id'], ['id'])
    op.create_foreign_key(op.f('fk_workflow_decision_attachment_id_attachment'), 'workflow_decision', 'attachment', ['attachment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workflow_decision_attachment_id_attachment'), 'workflow_decision', type_='foreignkey')
    op.drop_constraint(op.f('fk_metadata_edition_approval_item_id_workflow_item'), 'metadata_edition', type_='foreignkey')
    op.drop_index(op.f('ix_entity_guid'), table_name='entity')
    op.drop_column('entity', 'guid')
    op.drop_constraint(op.f('fk_dataset_activated_item_id_workflow_item'), 'dataset', type_='foreignkey')
    # ### end Alembic commands ###
