"""Add guid to entities

Revision ID: f54486f1839b
Revises: 64dfbebe0ba8
Create Date: 2026-01-05 09:14:51.511798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54486f1839b'
down_revision = '64dfbebe0ba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset") as batch_op:
        batch_op.create_foreign_key(op.f('fk_dataset_activated_item_id_workflow_item'), 'workflow_item', ['activated_item_id'], ['id'])
    op.add_column('entity', sa.Column('guid', sa.String(length=255), nullable=True))
    with op.batch_alter_table('entity') as batch_op:
        batch_op.create_index(op.f('ix_entity_guid'), ['guid'], unique=False)
    with op.batch_alter_table('metadata_edition') as batch_op:
        batch_op.create_foreign_key(op.f('fk_metadata_edition_approval_item_id_workflow_item'), 'workflow_item', ['approval_item_id'], ['id'])
    with op.batch_alter_table("workflow_decision") as batch_op:
        batch_op.create_foreign_key(op.f('fk_workflow_decision_attachment_id_attachment'), 'attachment', ['attachment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow_decision") as batch_op:
        batch_op.drop_constraint(op.f('fk_workflow_decision_attachment_id_attachment'), type_='foreignkey')
    with op.batch_alter_table('metadata_edition') as batch_op:
        batch_op.drop_constraint(op.f('fk_metadata_edition_approval_item_id_workflow_item'), type_='foreignkey')
    with op.batch_alter_table("entity") as batch_op:
        batch_op.drop_index(op.f('ix_entity_guid'))
    op.drop_column('entity', 'guid')
    with op.batch_alter_table('dataset') as batch_op:
        batch_op.drop_constraint(op.f('fk_dataset_activated_item_id_workflow_item'), type_='foreignkey')
    # ### end Alembic commands ###
