"""empty message

Revision ID: version_0_0_1
Revises: 
Create Date: 2023-03-15 15:46:27.714998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'version_0_0_1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('display_names', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group')),
    sa.UniqueConstraint('short_name', name=op.f('uq_group_short_name'))
    )
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('source_info', sa.String(length=1024), nullable=True),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric'))
    )
    op.create_index(op.f('ix_metric_metric_name'), 'metric', ['metric_name'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('display_names', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization')),
    sa.UniqueConstraint('short_name', name=op.f('uq_organization_short_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=True),
    sa.Column('phash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('allowed_api_access', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('user_login_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('attempt_time', sa.DateTime(), nullable=False),
    sa.Column('remote_ip', sa.String(length=16), nullable=False),
    sa.Column('from_api', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('was_success', sa.Boolean(), nullable=False),
    sa.Column('was_since_last_clear', sa.Boolean(), nullable=False),
    sa.Column('lockable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_login_record'))
    )
    op.create_index(op.f('ix_user_login_record_username'), 'user_login_record', ['username'], unique=False)
    op.create_table('vocabulary_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('display_names', sa.Text(), nullable=True),
    sa.Column('descriptions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_term')),
    sa.UniqueConstraint('vocabulary_name', 'short_name', name='unique_vocab_short_term')
    )
    op.create_index(op.f('ix_vocabulary_term_vocabulary_name'), 'vocabulary_term', ['vocabulary_name'], unique=False)
    op.create_table('workflow_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('workflow_type', sa.String(length=255), nullable=True),
    sa.Column('workflow_name', sa.String(length=255), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('step_list', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('completed_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('locked_by', sa.String(length=36), nullable=True),
    sa.Column('locked_since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_item'))
    )
    op.create_index(op.f('ix_workflow_item_workflow_name'), 'workflow_item', ['workflow_name'], unique=False)
    op.create_index(op.f('ix_workflow_item_workflow_type'), 'workflow_item', ['workflow_type'], unique=False)
    op.create_table('a_p_i_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display', sa.String(length=1024), nullable=True),
    sa.Column('prefix', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=True),
    sa.Column('key_salt', sa.String(length=64), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('old_key_hash', sa.String(length=128), nullable=True),
    sa.Column('old_key_salt', sa.String(length=64), nullable=True),
    sa.Column('old_expiry', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_a_p_i_key_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_a_p_i_key'))
    )
    op.create_index(op.f('ix_a_p_i_key_prefix'), 'a_p_i_key', ['prefix'], unique=False)
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('display_names', sa.Text(), nullable=True),
    sa.Column('profiles', sa.Text(), nullable=True),
    sa.Column('pub_workflow', sa.String(length=255), nullable=False),
    sa.Column('act_workflow', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('security_level', sa.String(length=255), nullable=False),
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_dataset_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset')),
    sa.UniqueConstraint('guid', name=op.f('uq_dataset_guid'))
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('display_names', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parent_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_entity_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity'))
    )
    op.create_index(op.f('ix_entity_entity_type'), 'entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_organization_id'), 'entity', ['organization_id'], unique=False)
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_user_group_group_id_group')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_group_user_id_user'))
    )
    op.create_index(op.f('ix_user_group_group_id'), 'user_group', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_group_user_id'), 'user_group', ['user_id'], unique=False)
    op.create_table('user_organization',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_user_organization_organization_id_organization')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_organization_user_id_user'))
    )
    op.create_index(op.f('ix_user_organization_organization_id'), 'user_organization', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_organization_user_id'), 'user_organization', ['user_id'], unique=False)
    op.create_table('workflow_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_item_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=True),
    sa.Column('decider_id', sa.String(length=1024), nullable=False),
    sa.Column('decision', sa.Boolean(), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_item_id'], ['workflow_item.id'], name=op.f('fk_workflow_decision_workflow_item_id_workflow_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_decision'))
    )
    op.create_table('entity_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_entity_data_entity_id_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_data')),
    sa.UniqueConstraint('entity_id', 'revision_no', name='unique_entity_revision_data')
    )
    op.create_table('metadata_edition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('fk_metadata_edition_dataset_id_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata_edition')),
    sa.UniqueConstraint('dataset_id', 'revision_no', name='unique_dataset_revision_data')
    )
    op.create_table('user_dataset',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('fk_user_dataset_dataset_id_dataset')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_dataset_user_id_user'))
    )
    op.create_index(op.f('ix_user_dataset_dataset_id'), 'user_dataset', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_user_dataset_user_id'), 'user_dataset', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_dataset_user_id'), table_name='user_dataset')
    op.drop_index(op.f('ix_user_dataset_dataset_id'), table_name='user_dataset')
    op.drop_table('user_dataset')
    op.drop_table('metadata_edition')
    op.drop_table('entity_data')
    op.drop_table('workflow_decision')
    op.drop_index(op.f('ix_user_organization_user_id'), table_name='user_organization')
    op.drop_index(op.f('ix_user_organization_organization_id'), table_name='user_organization')
    op.drop_table('user_organization')
    op.drop_index(op.f('ix_user_group_user_id'), table_name='user_group')
    op.drop_index(op.f('ix_user_group_group_id'), table_name='user_group')
    op.drop_table('user_group')
    op.drop_index(op.f('ix_entity_organization_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_entity_type'), table_name='entity')
    op.drop_table('entity')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_a_p_i_key_prefix'), table_name='a_p_i_key')
    op.drop_table('a_p_i_key')
    op.drop_index(op.f('ix_workflow_item_workflow_type'), table_name='workflow_item')
    op.drop_index(op.f('ix_workflow_item_workflow_name'), table_name='workflow_item')
    op.drop_table('workflow_item')
    op.drop_index(op.f('ix_vocabulary_term_vocabulary_name'), table_name='vocabulary_term')
    op.drop_table('vocabulary_term')
    op.drop_index(op.f('ix_user_login_record_username'), table_name='user_login_record')
    op.drop_table('user_login_record')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('organization')
    op.drop_index(op.f('ix_metric_metric_name'), table_name='metric')
    op.drop_table('metric')
    op.drop_table('group')
    # ### end Alembic commands ###
