"""v1_1_0

Revision ID: 268c99fe82de
Revises: ac68493869d4
Create Date: 2023-04-20 15:59:57.965824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268c99fe82de'
down_revision = 'ac68493869d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
        sa.Column('file_name', sa.String(length=1024), nullable=False),
        sa.Column('storage_path', sa.String(length=1024), nullable=False),
        sa.Column('dataset_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('modified_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('storage_name', sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_attachment_created_by_user')),
        sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('fk_attachment_dataset_id_dataset')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    op.add_column('workflow_decision', sa.Column('comments', sa.Text(), nullable=True))
    op.add_column('workflow_decision', sa.Column('attachment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_workflow_decision_attachment_id_attachment'), 'workflow_decision', 'attachment', ['attachment_id'], ['id'])
    # ### end Alembic commands ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workflow_decision_attachment_id_attachment'), 'workflow_decision', type_='foreignkey')
    op.drop_column('workflow_decision', 'attachment_id')
    op.drop_column('workflow_decision', 'comments')
    op.drop_table('attachment')
    # ### end Alembic commands ###
