"""empty message

Revision ID: 75b4baae5479
Revises: f3c80a31ba5e
Create Date: 2023-04-11 21:06:54.249164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b4baae5479'
down_revision = 'f3c80a31ba5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_item', sa.Column('step_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_item', 'step_output')
    # ### end Alembic commands ###
