"""empty message

Revision ID: b68dade1fe82
Revises: version_0_0_1
Create Date: 2023-03-27 09:51:46.235000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68dade1fe82'
down_revision = 'version_0_0_1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_session',
    sa.Column('guid', sa.String(length=1024), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_session')),
    sa.UniqueConstraint('guid', name=op.f('uq_server_session_guid'))
    )
    op.alter_column('dataset', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_session')
    # ### end Alembic commands ###
