erddap:
  label:
    en: Core ERDDAP
  fields:
    erddap_dataset_id: yes
    cdm_data_type: yes
    processing_level: no
    project: no
    program: no
    title: yes
    abstract: no
    credit: no
    publication_date: yes
    info_link: yes
    short_institution: yes
    author: yes
    contributors: no
    contact_point: no
    revision_date: no
    creation_date: no
    custom_keywords: no
    topic_category: no
    iso_maintenance: no
    spatial_representation_type: yes
    content_coverage_type: no
    variables: yes
    license: yes
    erddap_dataset_type: yes
    erddap_data_file_path: yes
    erddap_data_file_pattern: yes
    standard_name_vocab: no
  formatters:
    erddapxml:
      label:
        en: ERDDAP XML
      template: erddap.xml
      preprocess: pipeman.builtins.erddap.util.preprocess_dataset
