erddap:
  label:
    en: Core ERDDAP
  validation:
    required:
      - erddap_dataset_id
      - cdm_data_type
      - title
      - publication_date
      - info_link
      - short_institution
      - author
      - spatial_representation_type
      - variables
      - erddap_data_file_path
      - erddap_dataset_type
      - licenses
      - erddap_data_file_pattern
    recommended:
      - abstract
  fields:
    erddap_dataset_id:
    cdm_data_type:
    processing_level:
    project:
    program:
    title:
    abstract:
    credit:
    publication_date:
    info_link:
    short_institution:
    author:
    contributors:
    contact_point:
    revision_date:
    creation_date:
    custom_keywords:
    topic_category:
    iso_maintenance:
    spatial_representation_type:
    content_coverage_type:
    variables:
    licenses:
    erddap_dataset_type:
    erddap_data_file_path:
    erddap_data_file_pattern:
    standard_name_vocab:
  formatters:
    erddapxml:
      label:
        en: ERDDAP XML
      template: erddap.xml
      preprocess: pipeman.builtins.erddap.util.preprocess_dataset
