iso19115:
  label:
    en: Core ISO-19115
  fields:
    title: yes
    abstract: no
    purpose: no
    pub_date: no
    credit: no
    publisher: yes
    owner: yes
    contributors: no
    doi: no
    info_link: no
    scope: no
    topic_category: no
    default_locale: no
    other_locales: no
  formatters:
    iso19115xml:
      label:
        en: ISO-19115 XML
      template: iso19115.xml
