iso19115:
  label:
    en: Core ISO-19115
  fields:
    contact_point:
      validation: required
    title:
      validation: required
    abstract:
      validation: required
    purpose:
    credit:
    doi:
    info_link:
    publication_date:
    revision_date:
    creation_date:
      validation: required
    publisher:
    author:
    contributors:
    topic_category:
    parent_metadata:
    alt_meta_refs:
    metadata_links:
    additional_docs:
    bbox_west:
    bbox_east:
    bbox_north:
    bbox_south:
    wkt_polygon:
    vertical_min:
    vertical_max:
    start_time:
    end_time:
    is_ongoing:
    spatial_resolution:
    temporal_resolution:
    horizontal_ref_system:
    vertical_ref_system:
    default_locale:
      validation: required
    other_locales:
    status:
    spatial_representation_type:
    resource_maintenance_frequency:
    metadata_maintenance_frequency:
    variables:
    iso_maintenance:
    custom_keywords:
    content_coverage_type:
    licenses:
      validation: required
    dataset_locale:
    dataset_other_locales:
    distributors:
    meta_licenses:
  formatters:
    iso19115xml:
      label:
        en: ISO-19115 XML
      template: iso19115.xml
      preprocess: pipeman.builtins.iso19115.util.preprocess_metadata